/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Connect: typeof import('./src/components/connect/index.vue')['default']
    Debug: typeof import('./src/components/debug/index.vue')['default']
    FrontPage: typeof import('./src/components/frontPage/index.vue')['default']
    Important: typeof import('./src/components/Important.vue')['default']
    Log: typeof import('./src/components/log/index.vue')['default']
    Setup: typeof import('./src/components/setup/index.vue')['default']
    Work: typeof import('./src/components/Work/index.vue')['default']
  }
}
